# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.cache/wt [current_project]
set_property parent.project_path C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/new/00.coe
add_files C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/imports/Desktop/imports/res/weights.coe
read_verilog -library xil_defaultlib {
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/Oled_Display.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/PetStatsSystem.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/alive_sprite.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/apple_sprite.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/bar_sprites.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/burger_sprite.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/button_detector.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/clock_6_25.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/coin_xp.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/collect_logic.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/collect_render.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/connect4.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/connect_button_debouncer.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/dead_sprite.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/exp.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/flappy_debounce.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/flappy_logic.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/flappy_render.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/game_menu.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/idle_scene.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/led_warning.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/left_arrow_sprite.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/lose_sprite.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/maplestory_background.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/imports/Desktop/mouse_cursor.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/oled_renderer.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/imports/Desktop/pet_jump_controller.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/pizza_sprite.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/right_arrow_sprite.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/segment_display.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/seven_seg_connect4.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/sevenseg_flappy.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/sevenseg_game.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/win_sprite.v
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/new/temporary_top.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/imports/Desktop/imports/Desktop/Mouse_Control.vhd
  C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/sources_1/imports/sources_1/imports/Desktop/imports/Desktop/Ps2Interface.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/constrs_1/imports/ee2026/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/risha/Desktop/projects/Tamagoonchi/Tamagoonchi.srcs/constrs_1/imports/ee2026/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
